### ISSUE TITLE
TestName link is redirecting to wrong category test

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports#260]
@anshooarora  

i'm running ma tests in parallel on mobile devices, i need to tag the devices under category so that i will get to know the status of tests on respective devices. 

When i navigate to the categories and click on the TestName it navigates to the wrong categories tests.

For Example:

Under Category i have Nexus 5 and when i select one of the TestClass which failed i was expecting it to navigate to the details of respective test under the Nexus 5 category, but it navigates to the same test but to some other category.

Please find the sample html uploaded 
https://drive.google.com/open?id=0B6xbSWlPu2cBYXlLelhBcTA0dk0

And the way its implemented as below :+1: 
https://github.com/saikrishna321/AppiumTestDistribution/tree/master/src/main/java/com/report/factory

And the impleneted class 

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java#L111

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java#L133

Is there anything that i'm missing in the implementation

**Comment by saikrishna321** [comment]
Sample Project to reproduce the bug 

https://github.com/saikrishna321/extent_reports

Open Extent.html and navigate to Thread-1 category and click on testApp7 and it takes you to details of testApp7 under Thread-0 not Thread-1.

**Comment by anshooarora** [comment]
I found this issue earlier in my testing and have already fixed.  Will add this into the next beta (beta-4) this week.

**Comment by saikrishna321** [comment]
@anshooarora thanks.. you don't have the beta version on maven repo ? If not, can you please look at jitpack

**Comment by anshooarora** [comment]
I will push a SNAPSHOT for this version to maven.  Will also look into Jitpack, very interesting.

**Comment by anshooarora** [comment]
Fixed in 17533caaa839988e5ace03819519d189a8dc79a5 by adding [extentid](https://github.com/anshooarora/extentreports/commit/17533caaa839988e5ace03819519d189a8dc79a5#diff-e3b7b4673ee291b1a0df41079a062391R287).

**Comment by anshooarora** [comment]
beta-4 jar and SNAPSHOT available [here](http://extentreports.relevantcodes.com/).

**Comment by saikrishna321** [comment]
@anshooarora i still don't see it under maven repo 

<img width="844" alt="screen shot 2016-01-12 at 10 17 51 am" src="https://cloud.githubusercontent.com/assets/4045041/12255042/7f92002e-b915-11e5-92ae-fe328e1e54f8.png">

**Comment by anshooarora** [comment]
Are you doing this via an ide?

I generally use command line against pom.xml and which works for snapshots:

```
mvn dependency:copy-dependencies
```

If you prefer ide, see [here](http://stackoverflow.com/questions/6111408/maven2-missing-artifact-but-jars-are-in-place).

**Comment by saikrishna321** [comment]
@anshooarora yes i'm doing it through IDE. 

Even running from commandline doesn't solve the problem

```
mvn dependency:copy-dependencies
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ExtentSamplesTest 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.relevantcodes:extentreports:jar:2.40.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.260 s
[INFO] Finished at: 2016-01-12T11:30:31+05:30
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ExtentSamplesTest: Could not resolve dependencies for project com.test.parallel:ExtentSamplesTest:jar:0.0.1-SNAPSHOT: Could not find artifact com.relevantcodes:extentreports:jar:2.40.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I cant see the SNAPSHOT version @ http://mvnrepository.com/artifact/com.relevantcodes/extentreports

**Comment by anshooarora** [comment]
Snapshot versions do not sync to central.  

Link to the latest snapshot:   https://oss.sonatype.org/content/repositories/snapshots/com/relevantcodes/extentreports/

**Comment by saikrishna321** [comment]
@anshooarora thanks mate, i had the add the sonatype repo url in the pom.xml 

Another stuff when i change the annotation to @BeforeClass from @BeforeMethod i don't get the reports generated. Please look at the code below 

```
	public ExtentTest testReporter;

	@BeforeClass
	public void beforeMethod(Method caller) {
		ExtentTestManager.startTest(caller.getName(), "This is a simple test.")
				.assignCategory(Thread.currentThread().getName());
	}

	@AfterClass
	public void afterMethod(ITestResult result) {
		if (result.isSuccess()) {
			ExtentTestManager.getTest().log(LogStatus.PASS, "Test passed");
		} else if (result.getStatus() == ITestResult.FAILURE) {
			ExtentTestManager.getTest().log(LogStatus.FAIL, "<pre>" + getStackTrace(result.getThrowable()) + "</pre>");
			System.out.println("******" + result.getThrowable().toString());

		} else if (result.getStatus() == ITestResult.SKIP) {
			ExtentTestManager.getTest().log(LogStatus.SKIP, "Test skipped");
		}

		ExtentTestManager.endTest();
		ExtentManager.getInstance().flush();
	}
```

**Comment by saikrishna321** [comment]
@anshooarora i see some issues with the report, don't close this issue will get back in a while

**Comment by saikrishna321** [comment]
@anshooarora when i switch to dark theme the UI is broken 

<img width="1437" alt="screen shot 2016-01-12 at 1 30 04 pm" src="https://cloud.githubusercontent.com/assets/4045041/12257901/4619145c-b930-11e5-8927-45a96cd9cbc2.png">


And i'm not to see the Exception View 

```
@BeforeClass
	public void beforeMethod() {
		ExtentTestManager.startTest(getClass().getName(), "This is a simple test.")
				.assignCategory(Thread.currentThread().getName());
	}

	@AfterMethod
	public void afterMethod(ITestResult result) {
		if (result.isSuccess()) {
			ExtentTestManager.getTest().log(LogStatus.PASS, result.getMethod().getMethodName());
		} else if (result.getStatus() == ITestResult.FAILURE) {
			//ExtentTestManager.getTest().log(LogStatus.FAIL, "<pre>" + getStackTrace(result.getThrowable()) + "</pre>");
			ExtentTestManager.getTest().log(LogStatus.FAIL,result.getMethod().getMethodName(),result.getThrowable().getMessage());		
     	} else if (result.getStatus() == ITestResult.SKIP) {
			ExtentTestManager.getTest().log(LogStatus.SKIP, result.getMethod().getMethodName());
		}

		
	}

	protected String getStackTrace(Throwable t) {
		StringWriter sw = new StringWriter();
		PrintWriter pw = new PrintWriter(sw);
		t.printStackTrace(pw);
		return sw.toString();
	}
	
	@AfterClass
	public void closeReport(){
		ExtentTestManager.endTest();
		ExtentManager.getInstance().flush();
	}
```

**Comment by anshooarora** [comment]
The dark theme is currently not complete as there were several updates to the UI, and all work was done on the core functionality.  Usually the last/final beta of a version has completeness in terms of styles which is why you see this behavior.  Feel free to make the necessary corrections towards this and I will merge your pull request.

For the exception view, as per the docs:

----

##### 2.40.1 Beta 3
Version 2.40.1-beta3 launched on 01/05/2016. Here is what's new:
* (#149) UX updates - containers are now resizable
* (#150) Exception View - This view is automatically created if an error is logged using the following logs:

```
log(LogStatus logStatus, Throwable t);
log(LogStatus logStatus, String stepName, Throwable t);
```
----

So all you have to do is:

```
ExtentTestManager
    .getTest()
    .log(
        LogStatus.FAIL, 
        result.getMethod().getMethodName(), 
        result.getThrowable()
    );
```

**Comment by anshooarora** [comment]
An updated dark theme will be available in 2.40.2, current beta available on extent website.
