### ISSUE TITLE
2.10 b2 time issue

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#83]
test.getTest().startedTime = getTime(Long
							.valueOf(startTime));
					test.getTest().endedTime = getTime(Long.valueOf(endTime));

Used to run for each test and the report would show something like:

![image](https://cloud.githubusercontent.com/assets/6800679/10071421/b6e65dac-6287-11e5-864d-53ac8efa4432.png)

The new report requires:

	test.getTest().setStartedTime(getTime(Long
							.valueOf(startTime)));
					test.getTest().setEndedTime(getTime(Long.valueOf(endTime)));

And shows:

![image](https://cloud.githubusercontent.com/assets/6800679/10071455/f3c0cc80-6287-11e5-8ef3-4f096670a975.png)

**Comment by cktech529** [comment]
Update: Beta 3.

![image](https://cloud.githubusercontent.com/assets/6800679/10078722/0a2dbd26-62b4-11e5-86e2-8326645a07fd.png)

Yes the tests show:

![image](https://cloud.githubusercontent.com/assets/6800679/10078729/16f78bc2-62b4-11e5-8783-a9e709d5e682.png)

**Comment by anshooarora** [comment]
I am unable to reproduce the timestamp error in any of my tests.  Can you help me reproduce?  

You can also move any of your test classes under the <a href='https://github.com/anshooarora/extentreports/tree/master/java/extentreports/src/test'>test</a> tree if that helps.

**Comment by cktech529** [comment]
My config is like the following:
Suite 
    Suite files (160 of them)  

Each suite file is a suite with a single <test> entry

I use Extent as a listener.

I do it this way so that when I run the suite in parallel (bump up the suite pool size to testng)

We get results for each test and timeouts work.

If I make it a single suite with 160 tests, there are testng issues :-/

It used to work though in 2.05 so if you changed the way your calculate total time between revisions, look there :).

 I'll keep digging. 

Chris

**Comment by anshooarora** [comment]
I see.  I didn't test it using the listener yet.  Will do it soon and fix in the next release.

**Comment by anshooarora** [comment]
I am able to reproduce with the listener.

A very non-elegant fix:

After the following line:

```
extent = new ExtentReports(outputDirectory + File.separator + "Extent.html", true);
```

insert:

```
String js = "function formatDt(d) {return d.getFullYear() + '-' +('00' + (d.getMonth() + 1)).slice(-2) + '-' + 	('00' + d.getDate()).slice(-2) + ' ' + 	('00' + d.getHours()).slice(-2) + ':' + 	('00' + d.getMinutes()).slice(-2) + ':' + 	('00' + d.getSeconds()).slice(-2);}function updateTotalTimeTaken() {var dates=[];$('.test-started-time, .test-ended-time').each(function() { dates.push(new Date($(this).text().replace('-', '/').replace('-', '/'))); });var maxDate=new Date(Math.max.apply(null,dates));var minDate=new Date(Math.min.apply(null,dates));$('.suite-started-time').text(formatDt(minDate));$('.suite-ended-time').text(formatDt(maxDate));var ended = $('.suite-ended-time').text().replace('-', '/').replace('-', '/');var started = $('.suite-started-time').text().replace('-', '/').replace('-', '/');var diff = new Date(new Date(ended) - new Date(started));var hours = Math.floor(diff / 36e5),minutes = Math.floor(diff % 36e5 / 60000),seconds = Math.floor(diff % 60000 / 1000);$('.suite-total-time-taken').text(hours + 'h ' + minutes + 'm ' + seconds + 's');}updateTotalTimeTaken();";
extent.config().insertJs(js);
```

The next release will have this inbuilt.

**Comment by cktech529** [comment]
Thanks!

**Comment by anshooarora** [comment]
fyi - beta-4 launched today, but this fix has still not been included as I am still experimenting with better ways of doing this when used from the listener.

**Comment by cktech529** [comment]
Yup, just downloaded 4 actually. was about to update you on it :)

**Comment by anshooarora** [comment]
The time issue using listener has been fixed now, in the final-beta.  A lot of minor changes to the layout as well.

**Comment by cktech529** [comment]
Looks great,

Thanks,

Chris

**Comment by MegaUkrainian** [comment]
Hi,

I've found that this issue is not resolved permanently in 2.40
Please recheck
![selection_059](https://cloud.githubusercontent.com/assets/13480390/11874889/81e6238a-a4ea-11e5-8bd0-cf7aa32f2277.jpg)

**Comment by anshooarora** [comment]
This one had popped again for users not using listener directly.  Was fixed a week ago in  #144.

**Comment by anshooarora** [comment]
Closing as issue was fixed in 2.40.2.
