### ISSUE TITLE
Test results not displayed in chronological order of execution

### ISSUE THREAD

**Issue by Deepak-Dave** [anshooarora/extentreports#93]
Firstly, The tests results displayed are not in the chronological order of execution. I am using the attribute DisplayOrder but still its showing the results in random sequence. I am using 2.05 version for Java and with testng and webdriver.

Please look into this issue.

![extent test order](https://cloud.githubusercontent.com/assets/14890235/10189582/b22cc9ca-6784-11e5-9cd5-1a030ee8579c.png)

The order of execution is in the alphabetical order i.e. as under

1. CCR_VD_AN_Test
2. CCR_VD_CH_Test
3. CCR_VD_CI_Test
4. CCR_VD_DN_Test
5. CCR_VD_EV_Test
6. CCR_VD_IN_Test
7. CCR_VD_MI_Test
8. CCR_VD_PL_Test
9. CCR_VD_SB_Test
10. CCR_VD_UR_Test

Also one more point. The category view shows the PASS and FAIL info correctly but it also shows other as 3. What are these 3 other ?

![category view extent](https://cloud.githubusercontent.com/assets/14890235/10189876/9b287c4a-6786-11e5-94ed-6084ecc29fdf.png)

**Comment by anshooarora** [comment]
For the first issue, looks like you are using the listener.  If you observe the listener code, you will notice that the results are added by status, and not by chronological order.  To generate tests chronologically, see here:  https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/reporters/SuiteHTMLReporter.java#L346.  You will have to modify your listener code to meet this requirement.

I am unable to reproduce the 2nd issue, but it is indeed very strange.  Can you upgrade to version 2.05 or 2.10 beta-5 (recommended) and try again?

**Comment by Deepak-Dave** [comment]
Yes, I am using the generating extent reports using the listener class. I have made many modifications in the listener code to meet my project requirements. The 2nd issue is currently trivial in my case, but the correct sequencing of tests is something that the client wants in the test reports. I am trying to see how i can make use of the code in the link you have mentioned.

Also I have tried to use the 2.10-beta-5 version, but there is compiler error in eclipse. I can't run the listener java code due to following 2 errors
1. The field Test.startedTime is not visible
2. The field Test.endedTime is not visible

![listener-2 10-beta-5 error](https://cloud.githubusercontent.com/assets/14890235/10214428/cd93e1ec-6835-11e5-94e8-49005d0640fa.png)

I suppose there will be no extent.db file to delete for users upto version 2.05. I have not used any 2.10-beta version yet and I did not find any such db file in my output/target directory.

How do I use the 2.10-beta versions given the above mentioned 2 compiler errors exist in eclipse ?

**Comment by dlitmano** [comment]
i have the same bug with Other:3 -> Version 2.05

**Comment by anshooarora** [comment]
Deepak, for listener using 2.10, see here:  https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ExtentReporterNG.java

Set time using:

```
test.getTest().setStartedTime(getTime(result.getStartMillis()));
test.getTest().setEndedTime(getTime(result.getEndMillis()));
```

If you do not have an extent.db file, ignore the message because for all users who have used 2.10 beta starting beta-1, there will be a database file created to store all information for your test runs.  No action to be performed if you do not have this.

dlitmano - can you try with version 2.10 also?

**Comment by anshooarora** [comment]
Also see here if you are using Reporter.log:

https://github.com/anshooarora/extentreports/issues/94#issuecomment-144499672

**Comment by Deepak-Dave** [comment]
Thanks Anshoo. I have run a few test cases with 2.10 beta-5. Interface looks good and perhaps better than 2.05. The Reporter.log is indeed a good and much required feature.

Is there some way test results can be sorted in the listener code based on the starting time of each test ? I am trying to think of a solution. Kindly suggest if u can think of one.

Also the 2nd issue of Others = 3 is now corrected and not appearing in the 2.10 beta-5 version.

Meanwhile, I have noticed 2 issues as given below 

1. I am unable to scroll down the HTML report page to the end. It scrolls down to approx 75 to 80% of the page and then auto scrolls to top of the page. I am not sure if it happens with others.

2. The test start time, end time and duration is correct in the test details view but showing duration as zero or same  start and end times in the Dashboard view.

![time test details](https://cloud.githubusercontent.com/assets/14890235/10262837/2d1af5e4-69f6-11e5-896b-7287539aec45.png)

![dashboard view time](https://cloud.githubusercontent.com/assets/14890235/10262838/3bc579a2-69f6-11e5-875e-9a53615bd1c7.png)

**Comment by anshooarora** [comment]
Both issues have been fixed in the final-beta (ready to be downloaded).

**Comment by Deepak-Dave** [comment]
The test duration in dashboard is showing correctly but the start and end times are still showing the same value i.e. start time is the same as end time. I am using 2.10 final beta version.

![dashboard time](https://cloud.githubusercontent.com/assets/14890235/10347282/c6cb5d16-6d50-11e5-8d31-8879a44b6720.png)

**Comment by anshooarora** [comment]
I am unable to reproduce this with normal logging or the listener.  Can you share me a test case along with your listener code?

**Comment by Deepak-Dave** [comment]
Hi Anshoo,
I got busy with some project work.

I am unable to attach any file format other than PNG, GIF or JPG due to lack of write permission. How do I send a sample test code so that you can reproduce the bug ?

Please find below the screenshots of html report for the bug regarding start and end timing in dashboard view.

I have attached the report for sample practice test on Mercury Test website to illustrate the issue. My actual tests can't be run without VPN and user authentication.

![test_result_1](https://cloud.githubusercontent.com/assets/14890235/10540206/b480a380-7423-11e5-9b29-c8cef7fbf1a4.png)

![test_result_2](https://cloud.githubusercontent.com/assets/14890235/10540212/bed4aa8e-7423-11e5-9737-bd68ab4c60fb.png)

**Comment by karthikbhatnagar** [comment]
Deepak
Are you still facing issue with this? I tested but its getting correct time info.

**Comment by Deepak-Dave** [comment]
Yes, Karthik. I am still getting this issue. I am using the latest version of extent reports now -- v 2.10. Why is this issue occuring here if you are not getting the same bug ?

I can send you a sample practice test code alongwith my extent listener code if I can attach file format like txt, doc, xls, pdf etc.

**Comment by anshooarora** [comment]
Deepak, can you test with the latest beta:  <a href='relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.11.0-beta-2.zip'>2.11.0-beta-2</a>.  A few fixes done from the listener's perspective.

**Comment by Deepak-Dave** [comment]
I have tested with the 2.11.0-beta-2. The test timing issue seems to be resolved. Only there is a difference of about 5 seconds in the test ending time and also in the test duration on comparing dashboard view and test details view.

Apart from that it looks fine.

**Comment by Deepak-Dave** [comment]
The test duration and timing disparity is more or less resolved and the requirement to chronologically arrange the scenarios was considered as not necessary by the client and was consequently given up.

Therefore I am closing this issue here.

**Comment by anshooarora** [comment]
Sorting will be introduced to arrange the test according to their end-times.

**Comment by aparnamaturi** [comment]
Hi 

I also have same problem that my TestNG emailable-report.html has test results in alphabetical order. I want the results in the order they were executed. In the last comment, you mentioned sorting will be introduced. Could you let me know which TestNG version has this feature? 

I understand we can write a custom listener and generate the whole HTML report with the sorting I need. But I want to use the default report with this sorting. Please let me know.

Thanks
Aparna

**Comment by aparnamaturi** [comment]
BTW, I am using testng 6.9.9 version.

**Comment by frederickishimwe** [comment]
**DisplayOrder newestfirst functionality on version 3.X**

Hi I am struggling to sort my test execution, everytime a new test build runs, I have to scroll through all the old test runs in order to find my  latest test right at the bottom, using the  

_.setAppendExisting(true)_

is there a way I could sort this to show the latest first ?

**Comment by Manasaranga90** [comment]
Report Status is not displaying 
![1](https://user-images.githubusercontent.com/37324994/37327803-bf54aa3c-26bd-11e8-8871-7f1608ab3204.png)
